module.exports = [
  // ETAPA 1 — MARCA, POSICIONAMENTO E IDENTIDADE (19 itens)
  { stage: 'Etapa 1 — Marca, Posicionamento e Identidade', description: 'Tem clareza do faturamento anual desejado', sort_order: 1 },
  { stage: 'Etapa 1 — Marca, Posicionamento e Identidade', description: 'Tem meta de faturamento mensal', sort_order: 2 },
  { stage: 'Etapa 1 — Marca, Posicionamento e Identidade', description: 'Tem meta de vendas semanal', sort_order: 3 },
  { stage: 'Etapa 1 — Marca, Posicionamento e Identidade', description: 'Sabe qual é a ação diária que gera vendas', sort_order: 4 },
  { stage: 'Etapa 1 — Marca, Posicionamento e Identidade', description: 'Tem diferenciais claros e comunicáveis e clareza do posicionamento no mercado', sort_order: 5 },
  { stage: 'Etapa 1 — Marca, Posicionamento e Identidade', description: 'Tem clareza de público-alvo', sort_order: 6 },
  { stage: 'Etapa 1 — Marca, Posicionamento e Identidade', description: 'Definiu palavras, jargões e símbolos associados à marca', sort_order: 7 },
  { stage: 'Etapa 1 — Marca, Posicionamento e Identidade', description: 'Definiu frase(s) ou conceito que represente a marca', sort_order: 8 },
  { stage: 'Etapa 1 — Marca, Posicionamento e Identidade', description: 'Escolheu pelo menos uma ação relacionada aos 5 sentidos da marca', sort_order: 9 },
  { stage: 'Etapa 1 — Marca, Posicionamento e Identidade', description: 'Criou rituais da marca (frase, trilha, experiência online ou offline)', sort_order: 10 },
  { stage: 'Etapa 1 — Marca, Posicionamento e Identidade', description: 'Criou playlist da marca (stories ou ambiente físico)', sort_order: 11 },
  { stage: 'Etapa 1 — Marca, Posicionamento e Identidade', description: 'Possui ensaio de fotos ou banco de imagens atualizado (até 1 ano)', sort_order: 12 },
  { stage: 'Etapa 1 — Marca, Posicionamento e Identidade', description: 'Logo, fontes e cores bem definidas', sort_order: 13 },
  { stage: 'Etapa 1 — Marca, Posicionamento e Identidade', description: 'Possui itens de assinatura de estilo pessoal ou da marca', sort_order: 14 },
  { stage: 'Etapa 1 — Marca, Posicionamento e Identidade', description: 'Se negócio local: está no Google Maps', sort_order: 15 },
  { stage: 'Etapa 1 — Marca, Posicionamento e Identidade', description: 'Se negócio digital: possui site ou página atualizada', sort_order: 16 },
  { stage: 'Etapa 1 — Marca, Posicionamento e Identidade', description: 'Pede avaliações dos clientes no Google', sort_order: 17 },
  { stage: 'Etapa 1 — Marca, Posicionamento e Identidade', description: 'Tem estrutura para coleta de depoimentos (prints ou formulário)', sort_order: 18 },
  { stage: 'Etapa 1 — Marca, Posicionamento e Identidade', description: 'Já pesquisou dores e desejos da audiência em formulários, stories ou conversas para extrair conteúdo disso', sort_order: 19 },

  // ETAPA 2 — CONTEÚDO E COMUNICAÇÃO (22 itens)
  { stage: 'Etapa 2 — Conteúdo e Comunicação', description: 'Definiu 3 temas principais da linha editorial', sort_order: 1 },
  { stage: 'Etapa 2 — Conteúdo e Comunicação', description: 'Criou lista de 60 ideias de conteúdo de gaveta', sort_order: 2 },
  { stage: 'Etapa 2 — Conteúdo e Comunicação', description: 'Mescla conteúdos que alegram, motivam, ensinam e vendem', sort_order: 3 },
  { stage: 'Etapa 2 — Conteúdo e Comunicação', description: 'Publica pelo menos 3 conteúdos por semana', sort_order: 4 },
  { stage: 'Etapa 2 — Conteúdo e Comunicação', description: 'Publica Reels pelo menos 2x na semana', sort_order: 5 },
  { stage: 'Etapa 2 — Conteúdo e Comunicação', description: 'Aparece em vídeo (stories ou feed) com frequência (pelo menos 3x na semana)', sort_order: 6 },
  { stage: 'Etapa 2 — Conteúdo e Comunicação', description: 'Todos os posts possuem legenda', sort_order: 7 },
  { stage: 'Etapa 2 — Conteúdo e Comunicação', description: 'Faz CTA nos posts', sort_order: 8 },
  { stage: 'Etapa 2 — Conteúdo e Comunicação', description: 'Faz CTA nos stories após falar do produto ou serviço pelo menos dia sim dia não', sort_order: 9 },
  { stage: 'Etapa 2 — Conteúdo e Comunicação', description: 'Mescla stories com foto, vídeo falando, vídeo do cotidiano e textos na tela', sort_order: 10 },
  { stage: 'Etapa 2 — Conteúdo e Comunicação', description: 'Cria pelo menos 1 story único por semana pra dobrar views com CTA após zerar stories do dia anterior ou ficar 24 horas sem postar', sort_order: 11 },
  { stage: 'Etapa 2 — Conteúdo e Comunicação', description: 'Cria pelo menos 1 story semanal com pergunta pedindo opinião da audiência no direct visando aumentar engajamento', sort_order: 12 },
  { stage: 'Etapa 2 — Conteúdo e Comunicação', description: 'Faz lives periodicamente', sort_order: 13 },
  { stage: 'Etapa 2 — Conteúdo e Comunicação', description: 'Utiliza estratégia de live invisível quando tem ações importantes', sort_order: 14 },
  { stage: 'Etapa 2 — Conteúdo e Comunicação', description: 'Tem modelos de design prontos no Canva', sort_order: 15 },
  { stage: 'Etapa 2 — Conteúdo e Comunicação', description: 'Possui padrão visual de feed alinhado à identidade da marca, sempre mesma cor, mesmas fontes, respeitando margens', sort_order: 16 },
  { stage: 'Etapa 2 — Conteúdo e Comunicação', description: 'Fotos bem tiradas e editadas (sem cortar pé, com fundo alinhado, seguindo regras dos terços)', sort_order: 17 },
  { stage: 'Etapa 2 — Conteúdo e Comunicação', description: 'Usa palavras de identificação (cidade, nicho etc.) nas legendas', sort_order: 18 },
  { stage: 'Etapa 2 — Conteúdo e Comunicação', description: 'Mostra preços quando vende produto físico', sort_order: 19 },
  { stage: 'Etapa 2 — Conteúdo e Comunicação', description: 'Tem rotina semanal de planejamento de conteúdo (um momento fixo pra gravar por exemplo)', sort_order: 20 },
  { stage: 'Etapa 2 — Conteúdo e Comunicação', description: 'Analisa mensalmente o desempenho dos conteúdos (avalia os que mais trouxeram seguidores, mais tiveram compartilhamentos)', sort_order: 21 },
  { stage: 'Etapa 2 — Conteúdo e Comunicação', description: 'Repete conteúdos que performam melhor', sort_order: 22 },

  // FORMATO DE CONTEÚDO ESTRATÉGICO (5 itens)
  { stage: 'Formato de Conteúdo Estratégico', description: 'Pesquisou na busca do Instagram os formatos mais visualizados do nicho', sort_order: 1 },
  { stage: 'Formato de Conteúdo Estratégico', description: 'Identificou padrões de conteúdo que mais performam no nicho', sort_order: 2 },
  { stage: 'Formato de Conteúdo Estratégico', description: 'Testou vários formatos de conteúdo', sort_order: 3 },
  { stage: 'Formato de Conteúdo Estratégico', description: 'Identificou 2 ou 3 formatos campeões', sort_order: 4 },
  { stage: 'Formato de Conteúdo Estratégico', description: 'Repete os formatos campeões pelo menos 2x por semana', sort_order: 5 },

  // ETAPA 3 — INSTAGRAM E VENDAS (9 itens)
  { stage: 'Etapa 3 — Instagram e Vendas', description: 'Bio ajustada conforme EPPC (especialidade, promessa, prova, CTA)', sort_order: 1 },
  { stage: 'Etapa 3 — Instagram e Vendas', description: 'Destaque e post fixado de apresentação da empresa ou da pessoa', sort_order: 2 },
  { stage: 'Etapa 3 — Instagram e Vendas', description: 'Destaque com serviços, horários ou link de compra', sort_order: 3 },
  { stage: 'Etapa 3 — Instagram e Vendas', description: 'Capas de destaque alinhadas com identidade visual (pode ser foto com cores)', sort_order: 4 },
  { stage: 'Etapa 3 — Instagram e Vendas', description: 'Tem posts fixados estratégicos no perfil', sort_order: 5 },
  { stage: 'Etapa 3 — Instagram e Vendas', description: 'Usa o recurso Notas do Instagram com frequência', sort_order: 6 },
  { stage: 'Etapa 3 — Instagram e Vendas', description: 'Possui respostas rápidas para dúvidas frequentes', sort_order: 7 },
  { stage: 'Etapa 3 — Instagram e Vendas', description: 'Mantém stories ativos diariamente', sort_order: 8 },
  { stage: 'Etapa 3 — Instagram e Vendas', description: 'Cuida os ganchos iniciais dos conteúdos', sort_order: 9 },

  // ETAPA 4 — TRÁFEGO, ESCALA E ANÁLISE (11 itens)
  { stage: 'Etapa 4 — Tráfego, Escala e Análise', description: 'Pesquisou criativos do nicho na biblioteca de anúncios', sort_order: 1 },
  { stage: 'Etapa 4 — Tráfego, Escala e Análise', description: 'Turbina conteúdos que já performaram bem pra crescimento de audiência', sort_order: 2 },
  { stage: 'Etapa 4 — Tráfego, Escala e Análise', description: 'Se negócio físico, tem um criativo rodando mostrando empresa, fachada, tour pela loja ou clínica ou salão para reconhecimento de marca/alcance', sort_order: 3 },
  { stage: 'Etapa 4 — Tráfego, Escala e Análise', description: 'Possui campanhas de tráfego para público frio', sort_order: 4 },
  { stage: 'Etapa 4 — Tráfego, Escala e Análise', description: 'Possui campanhas de tráfego para público quente', sort_order: 5 },
  { stage: 'Etapa 4 — Tráfego, Escala e Análise', description: 'Entende diferença entre alcance, clique e conversão', sort_order: 6 },
  { stage: 'Etapa 4 — Tráfego, Escala e Análise', description: 'Testa múltiplos criativos em imagens e vídeo nos anúncios e atualiza eles com frequência (pelo menos 5 a 10 novos toda semana ou todo mês)', sort_order: 7 },
  { stage: 'Etapa 4 — Tráfego, Escala e Análise', description: 'Legendas dos anúncios possuem identificação e CTA', sort_order: 8 },
  { stage: 'Etapa 4 — Tráfego, Escala e Análise', description: 'Já utilizou estratégia com influenciadores', sort_order: 9 },
  { stage: 'Etapa 4 — Tráfego, Escala e Análise', description: 'Se vende em site, possui pixel instalado', sort_order: 10 },
  { stage: 'Etapa 4 — Tráfego, Escala e Análise', description: 'Consegue acessar e analisar campanhas de anúncios', sort_order: 11 },

  // ETAPA 5 — ORGANIZAÇÃO, PROCESSOS E EQUIPE (9 itens)
  { stage: 'Etapa 5 — Organização, Processos e Equipe', description: 'Usa Google Agenda para organizar tarefas da empresa com dias fixos para certas funções como gravar', sort_order: 1 },
  { stage: 'Etapa 5 — Organização, Processos e Equipe', description: 'Possui Google Drive ou armazenamento organizado da empresa', sort_order: 2 },
  { stage: 'Etapa 5 — Organização, Processos e Equipe', description: 'Realiza reuniões periódicas com a equipe', sort_order: 3 },
  { stage: 'Etapa 5 — Organização, Processos e Equipe', description: 'Possui cronograma anual ou semestral de campanhas', sort_order: 4 },
  { stage: 'Etapa 5 — Organização, Processos e Equipe', description: 'Registra processos e instruções para tarefas repetitivas para trazer mais padrão e clareza pra equipe (exemplo: processo de atendimento, processo de pós venda)', sort_order: 5 },
  { stage: 'Etapa 5 — Organização, Processos e Equipe', description: 'Tem pelo menos uma assistente pessoal ou colaboradora para tarefas operacionais', sort_order: 6 },
  { stage: 'Etapa 5 — Organização, Processos e Equipe', description: 'Possui parceiro ou processo para recrutamento / empresa de RH, google forms pra preenchimento de vaga', sort_order: 7 },
  { stage: 'Etapa 5 — Organização, Processos e Equipe', description: 'Mantém grupo interno de comunicação com equipe e grupo de checkin (onde cada um manda um breve relatório do que realizou no dia anterior)', sort_order: 8 },
  { stage: 'Etapa 5 — Organização, Processos e Equipe', description: 'Faz pesquisa com equipe pra conhecer melhor o time (perguntas sobre sonhos, o que é importante, o que mais gosta, o que não gosta, o que melhoraria na empresa)', sort_order: 9 },

  // ETAPA 6 — INTELIGÊNCIA ARTIFICIAL E PRODUTIVIDADE (6 itens)
  { stage: 'Etapa 6 — Inteligência Artificial e Produtividade', description: 'Possui projetos organizados no ChatGPT para tarefas recorrentes', sort_order: 1 },
  { stage: 'Etapa 6 — Inteligência Artificial e Produtividade', description: 'Utiliza agentes ou ferramentas de IA para marketing', sort_order: 2 },
  { stage: 'Etapa 6 — Inteligência Artificial e Produtividade', description: 'Cria prompts personalizados para equipe ou clientes', sort_order: 3 },
  { stage: 'Etapa 6 — Inteligência Artificial e Produtividade', description: 'Gera imagens ou criativos com IA', sort_order: 4 },
  { stage: 'Etapa 6 — Inteligência Artificial e Produtividade', description: 'Usa IA para analisar dados e planejar ações', sort_order: 5 },
  { stage: 'Etapa 6 — Inteligência Artificial e Produtividade', description: 'Está desenvolvendo ou utilizando agentes próprios', sort_order: 6 },

  // ETAPA 7 — VENDAS E WHATSAPP (15 itens)
  { stage: 'Etapa 7 — Vendas e WhatsApp', description: 'Tem grupo de clientes ou lista de leads no WhatsApp', sort_order: 1 },
  { stage: 'Etapa 7 — Vendas e WhatsApp', description: 'Cria mensalmente ou semanalmente ações de vendas com compre 1 leve 2, compre e concorra, compre e pegue algo (com direito a brindes), combos, traga uma amiga, e similares', sort_order: 2 },
  { stage: 'Etapa 7 — Vendas e WhatsApp', description: 'Tem uma agenda de eventos ao longo do ano', sort_order: 3 },
  { stage: 'Etapa 7 — Vendas e WhatsApp', description: 'Cria ações ou eventos para aumentar o senso de comunidade com clientes com experiências', sort_order: 4 },
  { stage: 'Etapa 7 — Vendas e WhatsApp', description: 'Trabalha com cashback ou algum programa de fidelização (desconto para ex-clientes, pontos)', sort_order: 5 },
  { stage: 'Etapa 7 — Vendas e WhatsApp', description: 'Tem alguma ação no aniversário de clientes (seja uma mensagem, um mimo, um voucher)', sort_order: 6 },
  { stage: 'Etapa 7 — Vendas e WhatsApp', description: 'Possui script de atendimento (boas-vindas, proposta e fechamento) para facilitar padronização', sort_order: 7 },
  { stage: 'Etapa 7 — Vendas e WhatsApp', description: 'Possui IA no pré-atendimento do WhatsApp', sort_order: 8 },
  { stage: 'Etapa 7 — Vendas e WhatsApp', description: 'Tem CRM para controle de clientes e leads', sort_order: 9 },
  { stage: 'Etapa 7 — Vendas e WhatsApp', description: 'Faz follow-up com leads que não compraram chamando até 5x', sort_order: 10 },
  { stage: 'Etapa 7 — Vendas e WhatsApp', description: 'Chama clientes no WhatsApp para pós-venda e novas compras (se vende serviço, assim que vence botox ou na hora de retocar mechas, se vende produto, quando tem algo que chegou que é a cara da cliente)', sort_order: 11 },
  { stage: 'Etapa 7 — Vendas e WhatsApp', description: 'Faz prospecção ativa periodicamente interagindo com potenciais clientes no direct', sort_order: 12 },
  { stage: 'Etapa 7 — Vendas e WhatsApp', description: 'Tem clareza do ticket médio', sort_order: 13 },
  { stage: 'Etapa 7 — Vendas e WhatsApp', description: 'Cria ações ou metas pra aumentar ticket médio (sempre oferecer algo a mais para cliente, se vende produto oferece serviço, se vende serviço oferece produto)', sort_order: 14 },
  { stage: 'Etapa 7 — Vendas e WhatsApp', description: 'Tem clareza da margem de lucro', sort_order: 15 },
];
